# Generated by Django 4.2.7 on 2023-12-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fechaEstreno',
            field=models.DateField(null=True, verbose_name='Fecha de Estreno'),
        ),
    ]
